config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help', as: 'help'
  get '/about', to: 'static_pages#about'
  get '/contract', to: 'static_pages#contract'
  get '/signup', to: 'users#new'

  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: Settings.user.maxium_name_length }
  validates :email, presence: true, length: { maximum: Settings.user.maxium_email_length },
                    format: { with: /#{Settings.global.email_regex}/i }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: Settings.user.minium_password_length }

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create string, cost:
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute :remember_digest, User.digest(remember_token)

    remember_digest
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute :remember_digest, nil
  end

  def session_token
    remember_digest || remember
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def hello
    render html: 'Hello, world'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    login_params = params[:session]
    user = User.find_by email: login_params[:email]

    if user&.authenticate(login_params[:password])
      forwarding_url = session[:forwarding_url]
      reset_session
      login_params[:remember_me] == Settings.global.checkbox_true ? remember(user) : forget(user)
      login user
      redirect_to forwarding_url || user

    else
      flash[:danger] = t('.invalid_user')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout if logged_in?
    redirect_to root_url, status: :see_other
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contract; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[index edit update]
  before_action :correct_user, only: %i[edit update]
  before_action :admin_user, only: %i[destroy]

  def index
    print params
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      reset_session
      login @user
      flash[:success] = t('.success')
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = t('.success')
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    User.destroy_by(id: params[:id])

    flash[:success] = t('.success')
    redirect_to users_url, status: :see_other
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    return if logged_in?

    store_location
    flash[:danger] = t('.please_login')
    redirect_to login_url, status: :see_other
  end

  def correct_user
    @user = User.find_by(id: params[:id])
    return if current_user?(@user)

    redirect_to root_path, status: :see_other
  end

  def admin_user
    redirect_to root_path, status: :see_other unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    session[:session_token] = user.session_token
  end

  def current_user
    if (user_id = session[:user_id])
      user = User.find_by(id: user_id)

      return @current_user = user if user && session[:session_token] == user.session_token
    end

    return unless (user_id = cookies.encrypted[:user_id])

    user = User.find_by(id: user_id)
    return unless user&.authenticated?(cookies[:remember_token])

    login user
    @current_user = user
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    forget(current_user)
    reset_session
    @current_user = nil
  end

  def remember(user)
    user.remember

    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget

    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def current_user?(user)
    user && user == current_user
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def full_title(page_title = '')
    base_title = t('title')
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80)
    gravatar_id  = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to t('about'),   about_path %></li>
      <li><%= link_to t('contract'), contract_path %></li>
      <li><a href="https://news.railstutorial.org/"><%= t('news') %></a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t('app'), root_path, id: "logo" %>

    <nav>
      <div class="navbar-header">
        <button id="hamburger" type="button" class="navbar-toggle collapsed">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <ul id="navbar-menu" class="nav navbar-nav navbar-right collapse navbar-collapse">
        <li><%= link_to t('home'), root_path %></li>
        <li><%= link_to t('help'), help_path %></li>

        <% if logged_in? %>
        <li><%= link_to t('user'), users_path %></li>
        <li class="dropdown">
          <a href="#" id="account" class="dropdown-toggle"><%= t('account') %><b class="caret"></b></a>
        </li>
        <ul id="dropdown-menu" class="dropdown-menu">
          <li><%= link_to t('profile'), current_user %></li>
          <li><%= link_to t('settings'), edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li><%= link_to t('logout'), logout_path, data: { "turbo-method": :delete } %></li>
        </ul>
        <% else %>
        <li><%= link_to t('login'), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= full_title yield(:title) %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">

  <%= render 'layouts/rails_default' %>
  <%= render 'layouts/shim' %>
</head>

<body>
  <%= render 'layouts/header' %>

  <div class="container">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(@user.errors.count, "error") %>.
  </div>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, t('about')) %>

<h1>About</h1>
<p>
  The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
      Tutorial</em></a>, part of the
  <a href="https://www.learnenough.com/">Learn Enough</a> family of
  tutorials, is a
  <a href="https://www.railstutorial.org/book">book</a> and
  <a href="https://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="https://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample app for the tutorial.
</p>

app/views/static_pages/contract.html.erb
<% provide(:title, t("contract")) %>

<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://www.railstutorial.org/help">Rails Tutorial Help page</a>.
  To get help on this sample app, see the
  <a href="https://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em> book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, t('home')) %>

<div class="center jumbotron">
  <h1><%= t('app') %></h1>
  <p><%= t '.header' %></p>

  <%= link_to t('signup'), signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"), "https://rubyonrails.org/" %>
<!-- <%= image_tag("kitten.png", alt: "Kitten", width: "100%") %> -->

app/views/users/_form.html.erb
<%= form_with(model: @user) do |f| %>
  <%= render 'shared/error_messages' %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, t('confirmation') %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:save_button), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<% @users.each do |user| %>
  <li>
    <%= gravatar_for user, size: 50 %>
    <%= link_to user.name, user %>
    <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to :delete, user, data: { "turbo-method": :delete,
                                          turbo_confirm: t('users.index.ask_confirmation') } %>
    <% end %>
  </li>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, t(".edit_user")) %>
<% provide(:save_button, t('save_changes')) %>
<h1><%= t('.update_profile') %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank"><%= t('change') %></a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, t('.all_users')) %>
<h1>All users</h1>

<%= will_paginate @users %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate @users %>

app/views/users/new.html.erb
<% provide(:title, t('signup')) %>
<% provide(:save_button, t('.create_account')) %>

<h1><%= t('signup') %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>